MACOSX_SDK_VERSION:  # [osx]
  - 11.1             # [osx and arm64]
  - 10.14            # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 11.1                   # [osx and arm64]
  - 10.10                  # [osx and x86_64]
CONDA_BUILD_SYSROOT: # [osx and x86_64]
  - /opt/MacOSX10.14.sdk  # [osx and x86_64]
c_compiler:
  - clang_bootstrap  # [osx]
  # - gcc              # [linux]
  - vs2019           # [win]
cxx_compiler:
  - clang_bootstrap  # [osx]
  # - gxx              # [linux]
  - vs2019           # [win]
c_compiler_version:        # [osx]
  - 17                     # [osx]
cxx_compiler_version:      # [osx]
  - 17                     # [osx]
vc:
  - 14
