MACOSX_SDK_VERSION:  # [osx]
  - 11.0             # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.9                   # [osx]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2019           # [win]
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2019           # [win]
vc:
  - 14
