c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

c_compiler_version:   # [osx]
  - 20.1.8            # [osx]
cxx_compiler_version:
  - 20.1.8            # [osx]