c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

# Stage 2: Self-hosted build with clang 22
c_compiler_version:   # [osx]
  - 22.1.2            # [osx]
cxx_compiler_version:
  - 22.1.2            # [osx]

# Keep consistent with llvmdev and clangdev
c_compiler:        # [win]
  - vs2022         # [win]
cxx_compiler:      # [win]
  - vs2022         # [win]

c_stdlib_version:  # [win]
  - 2022.14        # [win]
