MACOSX_SDK_VERSION:  # [osx]
  - 11.1             # [osx and arm64]
  - 10.14            # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 11.1                   # [osx and arm64]
  - 10.10                  # [osx and x86_64]
CONDA_BUILD_SYSROOT: # [osx and x86_64]
  - /opt/MacOSX10.14.sdk  # [osx and x86_64]
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]
vc:
  - 14
# channel_sources:
#  - conda-forge/label/llvm_rc,conda-forge,defaults  # [not (osx and arm64)]
#  - https://conda-web.anaconda.org/conda-forge  # [osx and arm64]
c_compiler_version:     # [osx and x86_64]
  - "10.0.0"            # [osx and x86_64]
cxx_compiler_version:   # [osx and x86_64]
  - "10.0.0"            # [osx and x86_64]
