cross_platform:
  - osx-64                 # [osx]
  - osx-arm64              # [osx]
  - linux-64               # [linux64]
  - linux-aarch64          # [aarch64]
  - linux-ppc64le          # [ppc64le]
  - win-64                 # [win]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.9                   # [osx]
  - 11.0                   # [osx]
zip_keys:                  # [osx]
  - - cross_platform       # [osx]
    - MACOSX_DEPLOYMENT_TARGET  # [osx]
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]
vc:
  - 14
python:
  - 3.7
c_compiler_version:     # [osx]
  - "10.0.1"            # [osx]
cxx_compiler_version:   # [osx]
  - "10.0.1"            # [osx]

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge,defaults
channel_targets:
  - conda-forge llvm_rc
