MACOSX_SDK_VERSION:  # [osx]
  - 11.0             # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.9                   # [osx]
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]
vc:
  - 14
c_compiler_version:     # [osx]
  - "11.0.0"            # [osx]
cxx_compiler_version:   # [osx]
  - "11.0.0"            # [osx]

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge
channel_targets:
  - conda-forge llvm_rc
