{% set name = "compiler-rt-packages" %}
{% set version = "9.0.0" %}
{% set build_number = 1 %}
{% set sha256 = "56e4cd96dd1d8c346b07b4d6b255f976570c6f2389697347a6c3dcb9e820d10e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://releases.llvm.org/{{ version }}/compiler-rt-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    - no_codesign.diff
    - macosx_10_9.patch

build:
  number: {{ build_number }}
  # https://groups.google.com/forum/#!msg/llvm-dev/cQogF7NZcSw/gOVQDXWmCgAJ
  skip: true  # [win]

requirements:
  build:
    - cmake >=3.4.3
    - {{ compiler('cxx') }}
    - python
  host:
    - clangdev {{ version }}
    - llvmdev {{ version }}
    - libcxx {{ cxx_compiler_version }}  # [osx]

test:
  files:
    - test.c.in
  commands:
  {% set NEW_TARGET="10." ~ (((MACOSX_DEPLOYMENT_TARGET|default("10.13")).split(".")[1])|int + 1) %}
    - sed "s/@MACOSX_DEPLOYMENT_TARGET@/{{ NEW_TARGET }}/g" test.c.in > test.c
    - clang -mmacosx-version-min={{ MACOSX_DEPLOYMENT_TARGET }} test.c  # [osx]
    - test -f $PREFIX/lib/clang/{{ version }}/include/sanitizer/asan_interface.h  # [unix]

outputs:
  - name: compiler-rt_{{ target_platform }}
    build:
      noarch: generic
    requirements:
      build:
        - {{ compiler('cxx') }}
      run:
        - libcxx >={{ cxx_compiler_version }}  # [osx]
        - clang {{ version }}
        - clangxx {{ version }}
      run_constrained:
        - compiler-rt {{ version }}
    files:
      - lib/clang/{{ version }}/lib

  - name: compiler-rt
    requirements:
      - libcxx >={{ cxx_compiler_version }}  # [osx]
      - clang {{ version }}
      - clangxx {{ version }}
      - compiler-rt_{{ target_platform }} {{ version }}
    files:
      - lib/clang/{{ version }}/share
      - lib/clang/{{ version }}/include

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: compiler-rt runtime libraries
  description: |
    builtins - low-level target-specific hooks required by code generation and other
      runtime components
    sanitizer runtimes - AddressSanitizer, ThreadSanitizer, UndefinedBehaviorSanitizer,
      MemorySanitizer, LeakSanitizer, DataFlowSanitizer
    profile - library which is used to collect coverage information
    BlocksRuntime - target-independent implementation of Apple "Blocks" runtime
      interfaces

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - jakirkham
    - isuruf
