bot:
  abi_migration_branches:
  - 15.x
  - 14.x
provider:
  linux_ppc64le: default
  linux_aarch64: default
conda_forge_output_validation: true
channel_priority: flexible
build_platform:
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
# due to https://github.com/conda/conda-build/issues/4787
remote_ci_setup:
  - conda-forge-ci-setup=3
  - py-lief<0.12
